/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface DotFactoryFactoryInterface extends ethers.utils.Interface {
  functions: {
    "coordinator()": FunctionFragment;
    "deployedFactories(uint256)": FunctionFragment;
    "getFactories()": FunctionFragment;
    "deployFactory(uint256,bytes32)": FunctionFragment;
    "factory()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "coordinator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deployedFactories",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFactories",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deployFactory",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "coordinator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployedFactories",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFactories",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;

  events: {
    "newDotFactory(address,uint256,bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "newDotFactory"): EventFragment;
}

export class DotFactoryFactory extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: DotFactoryFactoryInterface;

  functions: {
    coordinator(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "coordinator()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    deployedFactories(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "deployedFactories(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    getFactories(
      overrides?: CallOverrides
    ): Promise<{
      0: string[];
    }>;

    "getFactories()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string[];
    }>;

    deployFactory(
      providerPubKey: BigNumberish,
      providerTitle: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "deployFactory(uint256,bytes32)"(
      providerPubKey: BigNumberish,
      providerTitle: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    factory(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "factory()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;
  };

  coordinator(overrides?: CallOverrides): Promise<string>;

  "coordinator()"(overrides?: CallOverrides): Promise<string>;

  deployedFactories(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "deployedFactories(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getFactories(overrides?: CallOverrides): Promise<string[]>;

  "getFactories()"(overrides?: CallOverrides): Promise<string[]>;

  deployFactory(
    providerPubKey: BigNumberish,
    providerTitle: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "deployFactory(uint256,bytes32)"(
    providerPubKey: BigNumberish,
    providerTitle: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  factory(overrides?: CallOverrides): Promise<string>;

  "factory()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    coordinator(overrides?: CallOverrides): Promise<string>;

    "coordinator()"(overrides?: CallOverrides): Promise<string>;

    deployedFactories(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "deployedFactories(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getFactories(overrides?: CallOverrides): Promise<string[]>;

    "getFactories()"(overrides?: CallOverrides): Promise<string[]>;

    deployFactory(
      providerPubKey: BigNumberish,
      providerTitle: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "deployFactory(uint256,bytes32)"(
      providerPubKey: BigNumberish,
      providerTitle: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    factory(overrides?: CallOverrides): Promise<string>;

    "factory()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    newDotFactory(dotfactory: null, PubKey: null, Title: null): EventFilter;
  };

  estimateGas: {
    coordinator(overrides?: CallOverrides): Promise<BigNumber>;

    "coordinator()"(overrides?: CallOverrides): Promise<BigNumber>;

    deployedFactories(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "deployedFactories(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFactories(overrides?: CallOverrides): Promise<BigNumber>;

    "getFactories()"(overrides?: CallOverrides): Promise<BigNumber>;

    deployFactory(
      providerPubKey: BigNumberish,
      providerTitle: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "deployFactory(uint256,bytes32)"(
      providerPubKey: BigNumberish,
      providerTitle: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    factory(overrides?: CallOverrides): Promise<BigNumber>;

    "factory()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    coordinator(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "coordinator()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deployedFactories(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "deployedFactories(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFactories(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getFactories()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deployFactory(
      providerPubKey: BigNumberish,
      providerTitle: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "deployFactory(uint256,bytes32)"(
      providerPubKey: BigNumberish,
      providerTitle: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    factory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "factory()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
