/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface MpoStorageInterface extends ethers.utils.Interface {
  functions: {
    "tallyAddress(uint256,address)": FunctionFragment;
    "getResponders()": FunctionFragment;
    "getAddressTally(uint256,address)": FunctionFragment;
    "addResponse(uint256,address)": FunctionFragment;
    "getQueryThreshold(uint256)": FunctionFragment;
    "getResponderAddress(uint256)": FunctionFragment;
    "getThreshold(uint256)": FunctionFragment;
    "reachedThreshold(uint256,address)": FunctionFragment;
    "getPrecision(uint256)": FunctionFragment;
    "getThresholdStatus(uint256,address)": FunctionFragment;
    "getDelta(uint256)": FunctionFragment;
    "setDelta(uint256,uint256)": FunctionFragment;
    "getNumResponders()": FunctionFragment;
    "setResponders(address[])": FunctionFragment;
    "getClientQueryId(uint256)": FunctionFragment;
    "getQueryStatus(uint256)": FunctionFragment;
    "getResponses(uint256)": FunctionFragment;
    "getAverage(uint256)": FunctionFragment;
    "tallyResponse(uint256,uint256)": FunctionFragment;
    "setQueryStatus(uint256,uint256)": FunctionFragment;
    "getAddressResponse(uint256,address)": FunctionFragment;
    "setClientQueryId(uint256,uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "setThreshold(uint256,uint256)": FunctionFragment;
    "getThresholdResponses(uint256)": FunctionFragment;
    "getTally(uint256,uint256)": FunctionFragment;
    "getAddressStatus(address)": FunctionFragment;
    "setPrecision(uint256,uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "addThresholdResponse(uint256,uint256)": FunctionFragment;
    "onlyOneResponse(uint256,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "tallyAddress",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getResponders",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAddressTally",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addResponse",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getQueryThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getResponderAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "reachedThreshold",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPrecision",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getThresholdStatus",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getDelta",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDelta",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNumResponders",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setResponders",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getClientQueryId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getQueryStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getResponses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAverage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tallyResponse",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setQueryStatus",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAddressResponse",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setClientQueryId",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setThreshold",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getThresholdResponses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTally",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAddressStatus",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setPrecision",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "addThresholdResponse",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "onlyOneResponse",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "tallyAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getResponders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAddressTally",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getQueryThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getResponderAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reachedThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPrecision",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getThresholdStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDelta", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setDelta", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getNumResponders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setResponders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClientQueryId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getQueryStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getResponses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAverage", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tallyResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setQueryStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAddressResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setClientQueryId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getThresholdResponses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTally", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAddressStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPrecision",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addThresholdResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onlyOneResponse",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export class MpoStorage extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: MpoStorageInterface;

  functions: {
    tallyAddress(
      queryId: BigNumberish,
      responder: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "tallyAddress(uint256,address)"(
      queryId: BigNumberish,
      responder: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getResponders(
      overrides?: CallOverrides
    ): Promise<{
      0: string[];
    }>;

    "getResponders()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string[];
    }>;

    getAddressTally(
      queryId: BigNumberish,
      responder: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getAddressTally(uint256,address)"(
      queryId: BigNumberish,
      responder: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    addResponse(
      queryId: BigNumberish,
      party: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "addResponse(uint256,address)"(
      queryId: BigNumberish,
      party: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getQueryThreshold(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "getQueryThreshold(uint256)"(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    getResponderAddress(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getResponderAddress(uint256)"(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    getThreshold(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getThreshold(uint256)"(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    reachedThreshold(
      queryId: BigNumberish,
      sender: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "reachedThreshold(uint256,address)"(
      queryId: BigNumberish,
      sender: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getPrecision(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getPrecision(uint256)"(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    getThresholdStatus(
      queryId: BigNumberish,
      party: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "getThresholdStatus(uint256,address)"(
      queryId: BigNumberish,
      party: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    getDelta(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getDelta(uint256)"(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    setDelta(
      queryId: BigNumberish,
      _delta: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setDelta(uint256,uint256)"(
      queryId: BigNumberish,
      _delta: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getNumResponders(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getNumResponders()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    setResponders(
      parties: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setResponders(address[])"(
      parties: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getClientQueryId(
      mpoId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getClientQueryId(uint256)"(
      mpoId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    getQueryStatus(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getQueryStatus(uint256)"(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    getResponses(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber[];
    }>;

    "getResponses(uint256)"(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber[];
    }>;

    getAverage(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber[];
    }>;

    "getAverage(uint256)"(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber[];
    }>;

    tallyResponse(
      queryId: BigNumberish,
      response: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "tallyResponse(uint256,uint256)"(
      queryId: BigNumberish,
      response: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setQueryStatus(
      queryId: BigNumberish,
      status: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setQueryStatus(uint256,uint256)"(
      queryId: BigNumberish,
      status: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getAddressResponse(
      queryId: BigNumberish,
      responder: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getAddressResponse(uint256,address)"(
      queryId: BigNumberish,
      responder: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    setClientQueryId(
      mpoId: BigNumberish,
      _clientQueryId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setClientQueryId(uint256,uint256)"(
      mpoId: BigNumberish,
      _clientQueryId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    owner(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "owner()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    setThreshold(
      queryId: BigNumberish,
      _threshold: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setThreshold(uint256,uint256)"(
      queryId: BigNumberish,
      _threshold: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getThresholdResponses(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber[];
    }>;

    "getThresholdResponses(uint256)"(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber[];
    }>;

    getTally(
      queryId: BigNumberish,
      response: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getTally(uint256,uint256)"(
      queryId: BigNumberish,
      response: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    getAddressStatus(
      party: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "getAddressStatus(address)"(
      party: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    setPrecision(
      queryId: BigNumberish,
      _precision: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setPrecision(uint256,uint256)"(
      queryId: BigNumberish,
      _precision: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    addThresholdResponse(
      queryId: BigNumberish,
      response: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "addThresholdResponse(uint256,uint256)"(
      queryId: BigNumberish,
      response: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    onlyOneResponse(
      queryId: BigNumberish,
      party: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "onlyOneResponse(uint256,address)"(
      queryId: BigNumberish,
      party: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;
  };

  tallyAddress(
    queryId: BigNumberish,
    responder: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "tallyAddress(uint256,address)"(
    queryId: BigNumberish,
    responder: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getResponders(overrides?: CallOverrides): Promise<string[]>;

  "getResponders()"(overrides?: CallOverrides): Promise<string[]>;

  getAddressTally(
    queryId: BigNumberish,
    responder: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getAddressTally(uint256,address)"(
    queryId: BigNumberish,
    responder: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  addResponse(
    queryId: BigNumberish,
    party: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "addResponse(uint256,address)"(
    queryId: BigNumberish,
    party: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getQueryThreshold(
    queryId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "getQueryThreshold(uint256)"(
    queryId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getResponderAddress(
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "getResponderAddress(uint256)"(
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getThreshold(
    queryId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getThreshold(uint256)"(
    queryId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  reachedThreshold(
    queryId: BigNumberish,
    sender: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "reachedThreshold(uint256,address)"(
    queryId: BigNumberish,
    sender: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getPrecision(
    queryId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getPrecision(uint256)"(
    queryId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getThresholdStatus(
    queryId: BigNumberish,
    party: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "getThresholdStatus(uint256,address)"(
    queryId: BigNumberish,
    party: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getDelta(
    queryId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getDelta(uint256)"(
    queryId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  setDelta(
    queryId: BigNumberish,
    _delta: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setDelta(uint256,uint256)"(
    queryId: BigNumberish,
    _delta: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getNumResponders(overrides?: CallOverrides): Promise<BigNumber>;

  "getNumResponders()"(overrides?: CallOverrides): Promise<BigNumber>;

  setResponders(
    parties: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setResponders(address[])"(
    parties: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getClientQueryId(
    mpoId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getClientQueryId(uint256)"(
    mpoId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getQueryStatus(
    queryId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getQueryStatus(uint256)"(
    queryId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getResponses(
    queryId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  "getResponses(uint256)"(
    queryId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  getAverage(
    queryId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  "getAverage(uint256)"(
    queryId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  tallyResponse(
    queryId: BigNumberish,
    response: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "tallyResponse(uint256,uint256)"(
    queryId: BigNumberish,
    response: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setQueryStatus(
    queryId: BigNumberish,
    status: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setQueryStatus(uint256,uint256)"(
    queryId: BigNumberish,
    status: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getAddressResponse(
    queryId: BigNumberish,
    responder: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getAddressResponse(uint256,address)"(
    queryId: BigNumberish,
    responder: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  setClientQueryId(
    mpoId: BigNumberish,
    _clientQueryId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setClientQueryId(uint256,uint256)"(
    mpoId: BigNumberish,
    _clientQueryId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  setThreshold(
    queryId: BigNumberish,
    _threshold: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setThreshold(uint256,uint256)"(
    queryId: BigNumberish,
    _threshold: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getThresholdResponses(
    queryId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  "getThresholdResponses(uint256)"(
    queryId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  getTally(
    queryId: BigNumberish,
    response: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getTally(uint256,uint256)"(
    queryId: BigNumberish,
    response: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getAddressStatus(party: string, overrides?: CallOverrides): Promise<boolean>;

  "getAddressStatus(address)"(
    party: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  setPrecision(
    queryId: BigNumberish,
    _precision: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setPrecision(uint256,uint256)"(
    queryId: BigNumberish,
    _precision: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  addThresholdResponse(
    queryId: BigNumberish,
    response: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "addThresholdResponse(uint256,uint256)"(
    queryId: BigNumberish,
    response: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  onlyOneResponse(
    queryId: BigNumberish,
    party: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "onlyOneResponse(uint256,address)"(
    queryId: BigNumberish,
    party: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    tallyAddress(
      queryId: BigNumberish,
      responder: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "tallyAddress(uint256,address)"(
      queryId: BigNumberish,
      responder: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getResponders(overrides?: CallOverrides): Promise<string[]>;

    "getResponders()"(overrides?: CallOverrides): Promise<string[]>;

    getAddressTally(
      queryId: BigNumberish,
      responder: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getAddressTally(uint256,address)"(
      queryId: BigNumberish,
      responder: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    addResponse(
      queryId: BigNumberish,
      party: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "addResponse(uint256,address)"(
      queryId: BigNumberish,
      party: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getQueryThreshold(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "getQueryThreshold(uint256)"(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getResponderAddress(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "getResponderAddress(uint256)"(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getThreshold(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getThreshold(uint256)"(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    reachedThreshold(
      queryId: BigNumberish,
      sender: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "reachedThreshold(uint256,address)"(
      queryId: BigNumberish,
      sender: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getPrecision(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getPrecision(uint256)"(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getThresholdStatus(
      queryId: BigNumberish,
      party: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "getThresholdStatus(uint256,address)"(
      queryId: BigNumberish,
      party: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getDelta(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getDelta(uint256)"(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setDelta(
      queryId: BigNumberish,
      _delta: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setDelta(uint256,uint256)"(
      queryId: BigNumberish,
      _delta: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getNumResponders(overrides?: CallOverrides): Promise<BigNumber>;

    "getNumResponders()"(overrides?: CallOverrides): Promise<BigNumber>;

    setResponders(parties: string[], overrides?: CallOverrides): Promise<void>;

    "setResponders(address[])"(
      parties: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    getClientQueryId(
      mpoId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getClientQueryId(uint256)"(
      mpoId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getQueryStatus(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getQueryStatus(uint256)"(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getResponses(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    "getResponses(uint256)"(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    getAverage(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    "getAverage(uint256)"(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    tallyResponse(
      queryId: BigNumberish,
      response: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "tallyResponse(uint256,uint256)"(
      queryId: BigNumberish,
      response: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setQueryStatus(
      queryId: BigNumberish,
      status: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setQueryStatus(uint256,uint256)"(
      queryId: BigNumberish,
      status: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getAddressResponse(
      queryId: BigNumberish,
      responder: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getAddressResponse(uint256,address)"(
      queryId: BigNumberish,
      responder: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setClientQueryId(
      mpoId: BigNumberish,
      _clientQueryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setClientQueryId(uint256,uint256)"(
      mpoId: BigNumberish,
      _clientQueryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    setThreshold(
      queryId: BigNumberish,
      _threshold: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setThreshold(uint256,uint256)"(
      queryId: BigNumberish,
      _threshold: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getThresholdResponses(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    "getThresholdResponses(uint256)"(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    getTally(
      queryId: BigNumberish,
      response: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getTally(uint256,uint256)"(
      queryId: BigNumberish,
      response: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAddressStatus(
      party: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "getAddressStatus(address)"(
      party: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    setPrecision(
      queryId: BigNumberish,
      _precision: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setPrecision(uint256,uint256)"(
      queryId: BigNumberish,
      _precision: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    addThresholdResponse(
      queryId: BigNumberish,
      response: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "addThresholdResponse(uint256,uint256)"(
      queryId: BigNumberish,
      response: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    onlyOneResponse(
      queryId: BigNumberish,
      party: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "onlyOneResponse(uint256,address)"(
      queryId: BigNumberish,
      party: string,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;
  };

  estimateGas: {
    tallyAddress(
      queryId: BigNumberish,
      responder: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "tallyAddress(uint256,address)"(
      queryId: BigNumberish,
      responder: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getResponders(overrides?: CallOverrides): Promise<BigNumber>;

    "getResponders()"(overrides?: CallOverrides): Promise<BigNumber>;

    getAddressTally(
      queryId: BigNumberish,
      responder: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getAddressTally(uint256,address)"(
      queryId: BigNumberish,
      responder: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    addResponse(
      queryId: BigNumberish,
      party: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "addResponse(uint256,address)"(
      queryId: BigNumberish,
      party: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getQueryThreshold(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getQueryThreshold(uint256)"(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getResponderAddress(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getResponderAddress(uint256)"(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getThreshold(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getThreshold(uint256)"(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    reachedThreshold(
      queryId: BigNumberish,
      sender: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "reachedThreshold(uint256,address)"(
      queryId: BigNumberish,
      sender: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getPrecision(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getPrecision(uint256)"(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getThresholdStatus(
      queryId: BigNumberish,
      party: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getThresholdStatus(uint256,address)"(
      queryId: BigNumberish,
      party: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDelta(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getDelta(uint256)"(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setDelta(
      queryId: BigNumberish,
      _delta: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setDelta(uint256,uint256)"(
      queryId: BigNumberish,
      _delta: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getNumResponders(overrides?: CallOverrides): Promise<BigNumber>;

    "getNumResponders()"(overrides?: CallOverrides): Promise<BigNumber>;

    setResponders(parties: string[], overrides?: Overrides): Promise<BigNumber>;

    "setResponders(address[])"(
      parties: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    getClientQueryId(
      mpoId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getClientQueryId(uint256)"(
      mpoId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getQueryStatus(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getQueryStatus(uint256)"(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getResponses(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getResponses(uint256)"(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAverage(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getAverage(uint256)"(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tallyResponse(
      queryId: BigNumberish,
      response: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "tallyResponse(uint256,uint256)"(
      queryId: BigNumberish,
      response: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setQueryStatus(
      queryId: BigNumberish,
      status: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setQueryStatus(uint256,uint256)"(
      queryId: BigNumberish,
      status: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getAddressResponse(
      queryId: BigNumberish,
      responder: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getAddressResponse(uint256,address)"(
      queryId: BigNumberish,
      responder: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setClientQueryId(
      mpoId: BigNumberish,
      _clientQueryId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setClientQueryId(uint256,uint256)"(
      mpoId: BigNumberish,
      _clientQueryId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    setThreshold(
      queryId: BigNumberish,
      _threshold: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setThreshold(uint256,uint256)"(
      queryId: BigNumberish,
      _threshold: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getThresholdResponses(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getThresholdResponses(uint256)"(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTally(
      queryId: BigNumberish,
      response: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getTally(uint256,uint256)"(
      queryId: BigNumberish,
      response: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAddressStatus(
      party: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getAddressStatus(address)"(
      party: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setPrecision(
      queryId: BigNumberish,
      _precision: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setPrecision(uint256,uint256)"(
      queryId: BigNumberish,
      _precision: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    addThresholdResponse(
      queryId: BigNumberish,
      response: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "addThresholdResponse(uint256,uint256)"(
      queryId: BigNumberish,
      response: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    onlyOneResponse(
      queryId: BigNumberish,
      party: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "onlyOneResponse(uint256,address)"(
      queryId: BigNumberish,
      party: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    tallyAddress(
      queryId: BigNumberish,
      responder: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "tallyAddress(uint256,address)"(
      queryId: BigNumberish,
      responder: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getResponders(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getResponders()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAddressTally(
      queryId: BigNumberish,
      responder: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getAddressTally(uint256,address)"(
      queryId: BigNumberish,
      responder: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addResponse(
      queryId: BigNumberish,
      party: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "addResponse(uint256,address)"(
      queryId: BigNumberish,
      party: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getQueryThreshold(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getQueryThreshold(uint256)"(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getResponderAddress(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getResponderAddress(uint256)"(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getThreshold(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getThreshold(uint256)"(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    reachedThreshold(
      queryId: BigNumberish,
      sender: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "reachedThreshold(uint256,address)"(
      queryId: BigNumberish,
      sender: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getPrecision(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getPrecision(uint256)"(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getThresholdStatus(
      queryId: BigNumberish,
      party: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getThresholdStatus(uint256,address)"(
      queryId: BigNumberish,
      party: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDelta(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getDelta(uint256)"(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setDelta(
      queryId: BigNumberish,
      _delta: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setDelta(uint256,uint256)"(
      queryId: BigNumberish,
      _delta: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getNumResponders(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getNumResponders()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setResponders(
      parties: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setResponders(address[])"(
      parties: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getClientQueryId(
      mpoId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getClientQueryId(uint256)"(
      mpoId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getQueryStatus(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getQueryStatus(uint256)"(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getResponses(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getResponses(uint256)"(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAverage(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getAverage(uint256)"(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tallyResponse(
      queryId: BigNumberish,
      response: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "tallyResponse(uint256,uint256)"(
      queryId: BigNumberish,
      response: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setQueryStatus(
      queryId: BigNumberish,
      status: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setQueryStatus(uint256,uint256)"(
      queryId: BigNumberish,
      status: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getAddressResponse(
      queryId: BigNumberish,
      responder: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getAddressResponse(uint256,address)"(
      queryId: BigNumberish,
      responder: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setClientQueryId(
      mpoId: BigNumberish,
      _clientQueryId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setClientQueryId(uint256,uint256)"(
      mpoId: BigNumberish,
      _clientQueryId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setThreshold(
      queryId: BigNumberish,
      _threshold: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setThreshold(uint256,uint256)"(
      queryId: BigNumberish,
      _threshold: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getThresholdResponses(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getThresholdResponses(uint256)"(
      queryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTally(
      queryId: BigNumberish,
      response: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getTally(uint256,uint256)"(
      queryId: BigNumberish,
      response: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAddressStatus(
      party: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getAddressStatus(address)"(
      party: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setPrecision(
      queryId: BigNumberish,
      _precision: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setPrecision(uint256,uint256)"(
      queryId: BigNumberish,
      _precision: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    addThresholdResponse(
      queryId: BigNumberish,
      response: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "addThresholdResponse(uint256,uint256)"(
      queryId: BigNumberish,
      response: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    onlyOneResponse(
      queryId: BigNumberish,
      party: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "onlyOneResponse(uint256,address)"(
      queryId: BigNumberish,
      party: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
