/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface MultiPartyOracleInterface extends ethers.utils.Interface {
  functions: {
    "callback(uint256,uint256[],bytes32[],uint8[],bytes32[])": FunctionFragment;
    "withdrawBalance()": FunctionFragment;
    "payout()": FunctionFragment;
    "spec3()": FunctionFragment;
    "storageAddress()": FunctionFragment;
    "setup(address[])": FunctionFragment;
    "receive(uint256,string,bytes32,bytes32[],bool)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "callback",
    values: [
      BigNumberish,
      BigNumberish[],
      BytesLike[],
      BigNumberish[],
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawBalance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "payout", values?: undefined): string;
  encodeFunctionData(functionFragment: "spec3", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "storageAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "setup", values: [string[]]): string;
  encodeFunctionData(
    functionFragment: "receive",
    values: [BigNumberish, string, BytesLike, BytesLike[], boolean]
  ): string;

  decodeFunctionResult(functionFragment: "callback", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "payout", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "spec3", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "storageAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setup", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "receive", data: BytesLike): Result;

  events: {
    "RecievedQuery(string,bytes32,bytes32[],address)": EventFragment;
    "ReceivedResponse(uint256,address,string)": EventFragment;
    "Incoming(uint256,address,address,string,bytes32,bytes32[],bool)": EventFragment;
    "Result1(uint256,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "RecievedQuery"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReceivedResponse"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Incoming"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Result1"): EventFragment;
}

export class MultiPartyOracle extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: MultiPartyOracleInterface;

  functions: {
    callback(
      mpoId: BigNumberish,
      responses: BigNumberish[],
      msgHash: BytesLike[],
      sigv: BigNumberish[],
      sigrs: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "callback(uint256,uint256[],bytes32[],uint8[],bytes32[])"(
      mpoId: BigNumberish,
      responses: BigNumberish[],
      msgHash: BytesLike[],
      sigv: BigNumberish[],
      sigrs: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    withdrawBalance(overrides?: Overrides): Promise<ContractTransaction>;

    "withdrawBalance()"(overrides?: Overrides): Promise<ContractTransaction>;

    payout(overrides?: Overrides): Promise<ContractTransaction>;

    "payout()"(overrides?: Overrides): Promise<ContractTransaction>;

    spec3(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "spec3()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    storageAddress(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "storageAddress()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    setup(
      _responders: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setup(address[])"(
      _responders: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    receive(
      id: BigNumberish,
      userQuery: string,
      endpoint: BytesLike,
      endpointParams: BytesLike[],
      onchainSubscriber: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "receive(uint256,string,bytes32,bytes32[],bool)"(
      id: BigNumberish,
      userQuery: string,
      endpoint: BytesLike,
      endpointParams: BytesLike[],
      onchainSubscriber: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  callback(
    mpoId: BigNumberish,
    responses: BigNumberish[],
    msgHash: BytesLike[],
    sigv: BigNumberish[],
    sigrs: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "callback(uint256,uint256[],bytes32[],uint8[],bytes32[])"(
    mpoId: BigNumberish,
    responses: BigNumberish[],
    msgHash: BytesLike[],
    sigv: BigNumberish[],
    sigrs: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  withdrawBalance(overrides?: Overrides): Promise<ContractTransaction>;

  "withdrawBalance()"(overrides?: Overrides): Promise<ContractTransaction>;

  payout(overrides?: Overrides): Promise<ContractTransaction>;

  "payout()"(overrides?: Overrides): Promise<ContractTransaction>;

  spec3(overrides?: CallOverrides): Promise<string>;

  "spec3()"(overrides?: CallOverrides): Promise<string>;

  storageAddress(overrides?: CallOverrides): Promise<string>;

  "storageAddress()"(overrides?: CallOverrides): Promise<string>;

  setup(
    _responders: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setup(address[])"(
    _responders: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  receive(
    id: BigNumberish,
    userQuery: string,
    endpoint: BytesLike,
    endpointParams: BytesLike[],
    onchainSubscriber: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "receive(uint256,string,bytes32,bytes32[],bool)"(
    id: BigNumberish,
    userQuery: string,
    endpoint: BytesLike,
    endpointParams: BytesLike[],
    onchainSubscriber: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    callback(
      mpoId: BigNumberish,
      responses: BigNumberish[],
      msgHash: BytesLike[],
      sigv: BigNumberish[],
      sigrs: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    "callback(uint256,uint256[],bytes32[],uint8[],bytes32[])"(
      mpoId: BigNumberish,
      responses: BigNumberish[],
      msgHash: BytesLike[],
      sigv: BigNumberish[],
      sigrs: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawBalance(overrides?: CallOverrides): Promise<void>;

    "withdrawBalance()"(overrides?: CallOverrides): Promise<void>;

    payout(overrides?: CallOverrides): Promise<void>;

    "payout()"(overrides?: CallOverrides): Promise<void>;

    spec3(overrides?: CallOverrides): Promise<string>;

    "spec3()"(overrides?: CallOverrides): Promise<string>;

    storageAddress(overrides?: CallOverrides): Promise<string>;

    "storageAddress()"(overrides?: CallOverrides): Promise<string>;

    setup(_responders: string[], overrides?: CallOverrides): Promise<void>;

    "setup(address[])"(
      _responders: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    receive(
      id: BigNumberish,
      userQuery: string,
      endpoint: BytesLike,
      endpointParams: BytesLike[],
      onchainSubscriber: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "receive(uint256,string,bytes32,bytes32[],bool)"(
      id: BigNumberish,
      userQuery: string,
      endpoint: BytesLike,
      endpointParams: BytesLike[],
      onchainSubscriber: boolean,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    RecievedQuery(
      query: null,
      endpoint: null,
      params: null,
      sender: null
    ): EventFilter;

    ReceivedResponse(
      queryId: null,
      responder: null,
      response: null
    ): EventFilter;

    Incoming(
      id: null,
      provider: null,
      subscriber: null,
      query: null,
      endpoint: null,
      endpointParams: null,
      onchainSubscriber: null
    ): EventFilter;

    Result1(id: null, response1: null): EventFilter;
  };

  estimateGas: {
    callback(
      mpoId: BigNumberish,
      responses: BigNumberish[],
      msgHash: BytesLike[],
      sigv: BigNumberish[],
      sigrs: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "callback(uint256,uint256[],bytes32[],uint8[],bytes32[])"(
      mpoId: BigNumberish,
      responses: BigNumberish[],
      msgHash: BytesLike[],
      sigv: BigNumberish[],
      sigrs: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    withdrawBalance(overrides?: Overrides): Promise<BigNumber>;

    "withdrawBalance()"(overrides?: Overrides): Promise<BigNumber>;

    payout(overrides?: Overrides): Promise<BigNumber>;

    "payout()"(overrides?: Overrides): Promise<BigNumber>;

    spec3(overrides?: CallOverrides): Promise<BigNumber>;

    "spec3()"(overrides?: CallOverrides): Promise<BigNumber>;

    storageAddress(overrides?: CallOverrides): Promise<BigNumber>;

    "storageAddress()"(overrides?: CallOverrides): Promise<BigNumber>;

    setup(_responders: string[], overrides?: Overrides): Promise<BigNumber>;

    "setup(address[])"(
      _responders: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    receive(
      id: BigNumberish,
      userQuery: string,
      endpoint: BytesLike,
      endpointParams: BytesLike[],
      onchainSubscriber: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "receive(uint256,string,bytes32,bytes32[],bool)"(
      id: BigNumberish,
      userQuery: string,
      endpoint: BytesLike,
      endpointParams: BytesLike[],
      onchainSubscriber: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    callback(
      mpoId: BigNumberish,
      responses: BigNumberish[],
      msgHash: BytesLike[],
      sigv: BigNumberish[],
      sigrs: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "callback(uint256,uint256[],bytes32[],uint8[],bytes32[])"(
      mpoId: BigNumberish,
      responses: BigNumberish[],
      msgHash: BytesLike[],
      sigv: BigNumberish[],
      sigrs: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    withdrawBalance(overrides?: Overrides): Promise<PopulatedTransaction>;

    "withdrawBalance()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    payout(overrides?: Overrides): Promise<PopulatedTransaction>;

    "payout()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    spec3(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "spec3()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    storageAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "storageAddress()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setup(
      _responders: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setup(address[])"(
      _responders: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    receive(
      id: BigNumberish,
      userQuery: string,
      endpoint: BytesLike,
      endpointParams: BytesLike[],
      onchainSubscriber: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "receive(uint256,string,bytes32,bytes32[],bool)"(
      id: BigNumberish,
      userQuery: string,
      endpoint: BytesLike,
      endpointParams: BytesLike[],
      onchainSubscriber: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
